# Generated by Django 3.1.3 on 2020-11-17 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('headline', models.CharField(max_length=60)),
                ('body', models.TextField(max_length=500)),
                ('heading_img_link', models.CharField(max_length=200)),
                ('sub_img_link_1', models.CharField(blank=True, max_length=200)),
                ('sub_img_link_2', models.CharField(blank=True, max_length=200)),
                ('sub_img_link_3', models.CharField(blank=True, max_length=200)),
                ('sub_img_link_4', models.CharField(blank=True, max_length=200)),
                ('sub_img_link_5', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
